### PR TITLE
Added cost for insertion and deletion in the weighted Levenshtein algo

### PR DESCRIPTION
**Pull request by glienard**
Added cost for insertion and deletion of characters in the weighted Levenshtein distance algorithm.

### CODE REVIEW

**Comment by glienard** [comment]
Hi @paulirwin , I've reverted those naming changes. Didn't know they were pulled as well.

**Comment by paulirwin** [comment]
Thanks for making those reverts. I just looked at the [upstream code](https://github.com/tdebatty/java-string-similarity/blob/master/src/main/java/info/debatty/java/stringsimilarity/WeightedLevenshtein.java) this library is ported from, and they added an extra interface instead of adding methods to the existing character substitution interface. Since we try to be as close to a 1:1 port of the upstream library as possible, I'll take their approach instead. But thanks for bringing this to our attention! We have likely a few other changes to catch this library up as well.

**Comment by paulirwin** [comment]
I have adopted the upstream approach in PR #16 to be reviewed by my team. Thanks for submitting this, but I'll close this in favor of #16 which catches this library up to version 1.2.0 of the upstream project.

**Comment by paulirwin** [comment]
Compatibility with java-string-similarity 1.2.0 has been released as [3.1.0 to NuGet](https://www.nuget.org/packages/F23.StringSimilarity/3.1.0).

**Pull request closed without merging**
