### PR TITLE
Upgrade netstandard2

### PR DESCRIPTION
**Pull request by iojancode**
Hi, no code changes, I did upgrade some project files and ran tests. It was easy to target multiple frameworks so I did restore support for .net framework 4.5 and at the same time support .net standard 2.0 which is used with a lot of applications nowadays.

### CODE REVIEW

**Comment by paulirwin** [comment]
Hi, apologies for the closure, renaming the default branch closed this PR. I'm working on merging it in now. Thanks!

**Comment by paulirwin** [comment]
This has been merged into develop. Sorry for the issue with the PR. Thanks!

**Comment by iojancode** [comment]
Should I make a new PR?

**Comment by iojancode** [comment]
reopen at #23

**Pull request closed without merging**
