### PR TITLE
Implementation of Ratcliff-Obershelp Algorithm

### PR DESCRIPTION
**Pull request by denmase**
It compiles and passes the test, but probably will need some more touch up.

compile

### CODE REVIEW

**Comment by paulirwin** [comment]
Thanks for this! I see that you submitted one upstream too. We do not do anything ahead of upstream, so I will look at your upstream PR and help review this week. Once that is merged in, we can account for any modifications that may have been made upstream, and adopt them here. Thank you for your contribution!

**Comment by paulirwin** [comment]
Now that has been merged upstream, we're ready to get this going here. Can you please update your files to use 4 spaces instead of tabs, and make sure any changes that were made to your upstream PR (including around whitespace) are updated here? No need to close and re-open PR, you can push extra changes to your master branch and it will update this one. Thanks!

**Comment by denmase** [comment]
Will do. I have question, I just saw that the naming convention (for variables) here is following upstream naming convention e.g.:
`small_profile` instead of `smallProfile` (camelCase) which I believe is the standard naming convention for C#.

Do you want me to follow the same naming convention as in upstream? I'm sorry for my amateurish work, never coded properly for a long time and in fact these were my first contribution to any open source projects. Thank you.

**Comment by paulirwin** [comment]
Thanks for your patience with the style preference 😄 Yes, we prefer to keep it as close to upstream as possible, with some small changes for things like interface names. Mainly because this helps us update our code to match upstream when bugs are fixed or otherwise the code changes.

**Comment by denmase** [comment]
Well, it's part of learning, right? :laughing: I think it's close enough, so I'll leave it to you whether further edit is required or not. Thank you

**Comment by paulirwin** [comment]
Sorry for the delay on this one, and sorry that the PR got closed when the branch was renamed to main. I'm working on merging this in now.

**Comment by paulirwin** [comment]
After looking into this further, unfortunately we cannot merge this in due to license conflicts. The fuzzystring implementation is under the Eclipse Public License, which requires re-use to be under the same license, which we are not (MIT). I would encourage the fuzzystring author to re-license in a more permissive (i.e. MIT) license that allows adaptation.

Note that I am being intentionally conservative here, given that this is a project provided by the company I work for. If any license-lawyer-experts have a different interpretation of the Eclipse PL, please definitely let me know. Thanks!

**Pull request closed without merging**
